### ISSUE TITLE
Patcher no longer works as intended

### ISSUE THREAD

**Issue by d9no** [7ap/internal-studio-patcher#8] opened 2024-09-05 00:46 UTC
Had no issues with patcher up until studio's update today, September 4th. I believe that the signature must've been changed.

Studio Version 0.641.0.6410737

**Comment by 7ap** [comment] 2024-09-05 02:21
Thanks for opening an issue. Yes, the signature is out of date as of v641. I'll look into this tomorrow.

**Comment by d9no** [comment] 2024-09-05 21:18
Great, thank you

**Comment by bluepilledgreat** [comment] 2024-09-05 21:37
> Thanks for opening an issue. Yes, the signature is out of date as of v641. I'll look into this tomorrow.

you

**Comment by uhKenobi** [comment] 2024-09-07 03:46
> Thanks for opening an issue. Yes, the signature is out of date as of v641. I'll look into this tomorrow.

😭

**Comment by 7ap** [comment] 2024-09-07 17:16
Pushed a fix.

Before I create a release, I would want a few other people to confirm it works for them.

**Comment by spidercraft** [comment] 2024-09-07 18:53
uuh, can you give me the link to it

**Comment by d9no** [comment] 2024-09-07 19:18
> Pushed a fix.
> 
> Before I create a release, I would want a few other people to confirm it works for them.

Is there a compilation? Would be happy to confirm if compiled 😅

**Comment by 7ap** [comment] 2024-09-07 19:20
Confirmed with a few friends, seems to be good. Download the binary for the latest release [here](https://github.com/7ap/internal-studio-patcher/releases/latest).

**Closed as completed by 7ap** 2024-09-07 19:20 UTC
